[icons]
# font awesome
TelegramDesktop = "ï‹†"
Thunderbird = "ïƒ "
# smile emoji
MyNiceProgram = "ğŸ˜›"

[aliases]
TelegramDesktop = "Telegram"
"Org.gnome.Nautilus" = "Nautilus"
firefox = "ï‰©"
kitty = "ï„ "
code-oss = "ï„¡"
discord = "ï„“"
Thunar = "î‹ˆ"
jetbrains-studio = "îŒ¤"
# "î‹‡" - Alternative
# "ï¼" - Broken

[general]
separator = " "
# default_icon = "ï„‘"
# default_alias = "ï„‘"
